homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 2108
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Denver

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor weather:
  platform: yr

# Text to speech
tts:
  platform: google

# Nest config
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# Xbox
sensor xbox:
  - platform: xbox_live
    api_key: !secret xbox_api_key
    xuid:
      - !secret xbox_xuid

# Moon
sensor moon:
  - platform: moon

# Network
sensor speedtest:
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload

device_tracker:
  - platform: netgear
    host: 192.168.1.1
    username: !secret netgear_username
    password: !secret netgear_password
    track_new_devices: false

# Apple TV
media_player appletv:
  - platform: apple_tv
    host: 192.168.1.21
    login_id: !secret appletv_login_id
